blank_issues_enabled: true
contact_links:
  - name: 📖 Dokumentation
    url: https://github.com/S540d/Energy_Price_Germany/blob/main/README.md
    about: Lies die Dokumentation für weitere Informationen
  - name: 💬 Diskussion
    url: https://github.com/S540d/Energy_Price_Germany/discussions
    about: Stelle Fragen oder diskutiere Ideen in GitHub Discussions
  - name: 🌐 Live Demo
    url: https://s540d.github.io/Energy_Price_Germany/
    about: Teste die App direkt im Browser
